### ISSUE TITLE
Issueベースの開発　レビュー依頼

### ISSUE THREAD

**Issue by kakuPAN** [kakuPAN/myapp#22]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。
本サービスは、「タスク管理✖︎街づくり」をテーマに、タスクをこなして街を発展させていく、ユーザー協力型ゲーム感覚のタスク管理サービスです。ユーザーが設定したタスクの達成率に応じてポイントが増加し、そのポイントが街の発展のために使用されます。逆に、設定されたタスクが期限以内に達成されなかった場合には、ポイントが減少します。そのポイントの多寡によって、街にあるオブジェクトが増えたり減ったりすることで、常に変化する街並みを楽しむことができます。タスクの設定以外にも、「さけぶ」という機能では、今の自分の気持ちを投稿すると、街の中に吹き出しとして出現させることができ、自分のタスク達成へのやる気を全ユーザーに表明することができます。

■1週間辺りの開発に向けられる時間
- 12/12まで　1週間あたり：15時間
- 12/12以降　1週間あたり：40時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/kakuPAN/projects/2

■MVPリリースまで
- [ ] docker 環境構築
- [ ] rails new
- [ ] AWS EC2 にデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] タスク作成機能
- [ ] タスク編集機能
- [ ] タスク閲覧機能
- [ ] オブジェクト表示機能
- [ ] つぶやき作成機能
- [ ] つぶやき表示機能
- [ ] リザルト表示機能
- [ ] メールアドレス変更
- [ ] パスワード変更

■MVP後
- [ ] イベント発生機能
- [ ] ポイント・オブジェクト変化の即時反映
- [ ] 昼夜の設定
- [ ] レスポンシブ対応
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] 独自ドメイン
- [ ] ファビコン

■MVPレビュー依頼予定日
予定日：2025年 1月 6日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- パスワード変更
- メールアドレス変更
- （つぶやき機能）
- （リザルト表示）

（）に含んだものはMVP時にサービスの検証として必要であれば実装を、そうでなければMVP後でも良いかと思いました。

**Comment by kakuPAN** [comment]
ありがとうございます。
MVP時に実装すべきか迷っていた部分になりますので、つぶやき機能、リザルト表示機能に関しては一度保留とし、時間的な余裕を鑑みて、検討したいと思います。
パスワード変更、メールアドレス変更部分はMVP後に実装としたいと思います。
