### ISSUE TITLE
MVPリリース　レビュー依頼

### ISSUE THREAD

**Issue by kakuPAN** [kakuPAN/myapp#47]
## 各種情報
サービスの概要とMVPで検証する事柄：
本サービスは、「タスク管理✖︎街づくり」をテーマに、タスクをこなして街を発展させていく、ユーザー協力型ゲーム感覚のタスク管理サービスです。ユーザーは自分で設定したタスクを達成することでポイントを稼ぐことができ、そのポイントが街の発展のために使用されます。そのポイントの多寡によって、街にあるオブジェクトが増えたり減ったりすることで、常に変化する街並みを楽しむことができます。

MVPでは、タスク管理サービスとしての最低限の機能を持たせています。ユーザー目線で現在の実装に足りない機能、改善点を絞り出し、タスク管理機能の面で洗練していくことを目的としています。
街づくり機能については、タスク管理をより楽しむため、継続して利用してもらうための要素として、今後実装予定です。

サービス名：街づくり×タスク管理

サービスURL：https://task-machi-app.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
：実装済み
- [x] タスク作成・編集・削除・閲覧・ステータス変更
：実装済み
- [ ] リザルト表示機能
：本リリース時に追加予定
- [ ] ポイント追加機能
：本リリース時に追加予定
- [ ] オブジェクト配置・削除機能
：本リリース時に追加予定
- [ ] つぶやき機能
：本リリース時に追加予定

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。
- 追加機能
・タスク検索機能
検索ボックスからタスクのタイトル・内容・作成者による検索、またチェックボックスからタスクの進行状況で検索をかけることができます。

- 本リリース時に追加予定の機能
以下、タスク管理サービスとしては追加機能にあたると判断したため、実装を延期しました。
・リザルト表示機能
・ポイント追加機能
・オブジェクト配置・削除機能
・つぶやき機能

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有してください。

### タスク作成
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/2a528145-7cb1-4e6a-809f-d612c4995e2d" />

### タスク一覧
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/99f6f274-3f97-4ca2-b3e5-e1ec6f8f0e7f" />

### タスク一覧　タスクの達成
<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/06bcc95f-647e-4c36-b84d-3a7d9e8a423d" />

### タスク検索フォーム
<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/d24a8b42-21fb-46b7-8682-d1b57117bdd4" />

**Comment by beppumasaki** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
